GET http://localhost:4000/carts
###
DELETE http://localhost:4000/carts/delete/all
###
GET http://localhost:4000/users-info
###
delete http://localhost:4000/doctorlist/delete/all

###
get https://meet.google.com/new